FROM nexus3.o-ran-sc.org:10002/o-ran-sc/bldr-ubuntu18-c-go:1.9.0

# ======================================================================

RUN apt-get update && apt-get install -y libpcap-dev && apt-get install -y libxml2-dev net-tools

ADD . /opt/o-du-l2

WORKDIR /opt/o-du-l2

RUN cd build/odu && make clean_odu odu MACHINE=BIT64 MODE=FDD

RUN cd build/odu && make clean_odu odu MACHINE=BIT64 MODE=FDD O1_ENABLE=NO

CMD /opt/o-du-l2/bin/odu/odu
